[package]
name = "interceptor-refactor"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = "1.10.1"
futures-core = "0.3.31"
futures-util = "0.3.31"
js-sys = "0.3.77"
reqwest = { version = "0.12.19", features = ["stream"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["js", "v4"] }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
wasm-streams = "0.4.2"
web-sys = { version = "0.3.77", features = [
    "console",
    "Response",
    "Request",
    "Url",
    "RequestInit",
    "ResponseInit",
    "Headers",
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "FormData",
    "Blob",
    "File",
    "UrlSearchParams",
    "RequestMode",
    "AbortSignal",
    "ReferrerPolicy",
] }


[dev-dependencies]
wasm-bindgen-test = "0.3.50"

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
