[package]
name = "interceptor-wasm"
version = "0.1.9"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["console", "Window", "Blob", "Event", "IdbTransactionMode",
    "IdbFactory", "IdbDatabase", "IdbTransaction", "IdbOpenDbRequest", "DomStringList", "IdbObjectStore",
    "IdbRequest", "IdbObjectStoreParameters", "DomException"] }
once_cell = "1.21.1"
reqwest = "0.12.15"
serde_json = "1.0.140"
serde-wasm-bindgen = "0.4"
bytes = "1.10.1"
js-sys = "0.3.77"

# ntor
hmac = "0.12"
sha2 = "0.10"
curve25519-dalek = "4.1.1"
x25519-dalek = {version="^2.0.1", features = ["static_secrets"] }
getrandom = { version = "0.2", features = ["js"] }
ntor = { git = "https://github.com/globe-and-citizen/ntor.git", branch = "thao/refactor" }
#ntor = { path = "../ntor" }

aes-gcm = "0.10"
serde = { version = "1.0.219", features = ["derive"] }


